[2023-12-08 01:01:02] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn f4124d176a5f5f8c 127.0.0.1:56457 failed checkpoint posthandshake: Connected to self
[2023-12-08 01:01:02] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn f4124d176a5f5f8c 127.0.0.1:20132 failed checkpoint posthandshake: Connected to self
[2023-12-08 01:01:08] [warning] account_manager.go:234 dpchain/accounts.(*Manager).GetAccount Account Manager: The account (f5bd17415c467039a442e9a5c871a74c819cd97a) can't be found!

[2023-12-08 01:01:08] [warning] dper.go:192 dpchain/ginHttp/router/api.InitRouter.UseAccount.func17 Http: Reply to user request -- UseAccount  warn:account with address: f5bd17415c467039a442e9a5c871a74c819cd97a cannot load, no such account is found

[2023-12-08 01:01:34] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn f4124d176a5f5f8c 127.0.0.1:56590 failed checkpoint posthandshake: Connected to self
[2023-12-08 01:01:34] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn f4124d176a5f5f8c 127.0.0.1:20132 failed checkpoint posthandshake: Connected to self
