[2023-12-14 12:33:19] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn 13229046edacba0b 127.0.0.1:63853 failed checkpoint posthandshake: Connected to self
[2023-12-14 12:33:19] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn 13229046edacba0b 127.0.0.1:20131 failed checkpoint posthandshake: Connected to self
[2023-12-14 12:33:27] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-12-14 12:33:27] [warning] peer.go:208 dpchain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2023-12-14 12:33:27] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-12-14 12:33:27] [error] dial.go:217 dpchain/p2p/server.(*dialTask).Do dial error: dial tcp 127.0.0.1:20130: connect: connection refused
