[2023-12-13 17:13:33] [warning] server.go:564 dpchain/p2p/server.(*Server).encHandshakeChecks 进行加密handshake: 节点已经与本机建立了连接

[2023-12-13 17:13:33] [warning] server.go:668 dpchain/p2p/server.(*Server).setupConn inbound conn 99d430df88c82261 127.0.0.1:61229 failed checkpoint addpeer: Already connected
[2023-12-13 17:13:33] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn cce471fc46e94029 127.0.0.1:61232 failed checkpoint posthandshake: Connected to self
[2023-12-13 17:13:33] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn cce471fc46e94029 127.0.0.1:20131 failed checkpoint posthandshake: Connected to self
