[2023-12-13 17:26:21] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn cce471fc46e94029 127.0.0.1:49547 failed checkpoint posthandshake: Connected to self
[2023-12-13 17:26:21] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn cce471fc46e94029 127.0.0.1:20131 failed checkpoint posthandshake: Connected to self
[2023-12-13 17:26:33] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-12-13 17:26:33] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-12-13 17:26:33] [warning] peer.go:208 dpchain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2023-12-13 17:26:33] [error] dial.go:217 dpchain/p2p/server.(*dialTask).Do dial error: dial tcp 127.0.0.1:20130: connect: connection refused
