[2023-12-13 17:26:19] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn inbound conn 99d430df88c82261 127.0.0.1:49534 failed checkpoint posthandshake: Connected to self
[2023-12-13 17:26:19] [warning] server.go:646 dpchain/p2p/server.(*Server).setupConn dyn dial conn 99d430df88c82261 127.0.0.1:20134 failed checkpoint posthandshake: Connected to self
[2023-12-13 17:26:33] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-12-13 17:26:33] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-12-13 17:26:33] [warning] peer.go:208 dpchain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2023-12-13 17:26:33] [error] dial.go:217 dpchain/p2p/server.(*dialTask).Do dial error: dial tcp 127.0.0.1:20130: connect: connection refused
[2023-12-13 17:26:33] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-12-13 17:26:33] [warning] peer.go:208 dpchain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2023-12-13 17:26:33] [error] dial.go:217 dpchain/p2p/server.(*dialTask).Do dial error: dial tcp 127.0.0.1:20131: connect: connection refused
[2023-12-13 17:26:33] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-12-13 17:26:33] [warning] synchronization.go:205 dpchain/blockSync.(*SyncProtocal).handleMsg Block synchronization failed: Couldn't Read the next message from the remote peer (cce471fc46e9402940bb2bcc4fbcee724dfcc14e020f6362ec2ad827bf6c4ef7354165b9de64807d37caae4888c31a86c34b77594ee64be150612991f6e95b61), err:EOF

[2023-12-13 17:26:33] [warning] peer.go:208 dpchain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2023-12-13 17:26:33] [warning] synchronization.go:205 dpchain/blockSync.(*SyncProtocal).handleMsg Block synchronization failed: Couldn't Read the next message from the remote peer (7d0efb28d2df0371574508110efbdfea0dcb408d91c250afeef29276dec1001bb18c33ae7d0f99edcfe39da384b73d9279f864ea5dfebf15cbe0c2e791951ac1), err:EOF

[2023-12-13 17:26:33] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-12-13 17:26:33] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-12-13 17:26:33] [error] dial.go:217 dpchain/p2p/server.(*dialTask).Do dial error: dial tcp 127.0.0.1:20132: connect: connection refused
[2023-12-13 17:26:33] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-12-13 17:26:33] [warning] peer.go:319 dpchain/p2p/server.(*Peer).startProtocols.func1 协议handshake, 协议Run函数错误,err:EOF

[2023-12-13 17:26:33] [warning] synchronization.go:205 dpchain/blockSync.(*SyncProtocal).handleMsg Block synchronization failed: Couldn't Read the next message from the remote peer (60dc34b7697c9058006d6f60e24048bb61c531142310decfc7970ac2921144984006dd9b95aafae167f3880497bf6741b5ed1f2c172d33fac779bada703dba6a), err:EOF

[2023-12-13 17:26:33] [warning] peer.go:208 dpchain/p2p/server.(*Peer).pingLoop heart beate, ping协程退出

[2023-12-13 17:26:33] [error] dial.go:217 dpchain/p2p/server.(*dialTask).Do dial error: dial tcp 127.0.0.1:20133: connect: connection refused
